config/routes.rb
Rails.application.routes.draw do
  get "dashboard/index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  get "pages/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "pages#index"

  resources :game_reviews
  resources :book_reviews do 
    collection do 
      get :fiction
      get :history
      get :non_fiction
      get :mystery
      get :science
      get :romance
      get :spirituality
      get :fantasy
    end
  end
  resources :articles
end

app/views/partials/_article_form.html.erb
<div class="general-review-form">
    <%= form_for(@article, url: url) do |f| %>
        <%= render "users/shared/error_messages", resource: @article %>
        
        <div class="field">
            <%= f.label :title, class: "" %>
            <%= f.text_field :title, class: "" %>
        </div>

        <div class="field">
            <%= f.label :author, class: "" %>
            <%= f.text_field :author, class: "" %>
        </div>

        <div class="field">
            <%= f.label "Attach", class: "" %>
            <%= f.file_field :avatars, multiple: "multiple" %>
        </div>

        <div class="field">
            <%= f.label :published, class: "" %>
            <%= f.date_field :published, class: "" %>
        </div>

        <div class="field">
            <%= f.label :tag, class: ""  %>
            <%= f.select :tag, options_for_select(['Science', 'Travel', 'Sport','Culture', 'Business', 'Innovation', 'Not Specified']), { prompt: " -- Select One -- "}, { class: "form-control", placeholder:" " } %> 
        </div>

        <div class="field">
            <%= f.label :short_description, class: "" %>
            <%= f.text_area :short_description, class: "", rows: 3, cols: 95 %>  
        </div>

        <div class="field">
            <%= f.label :content %>
            <%= f.text_area :content, class: "" %>
        </div>

        <div class="actions">
            <% if action == "new" %>
                <%= f.submit "Create", class: "", id: "" %>
            <% else %>
                <%= f.submit "Update", class: "", id: "" %>
            <% end %>
        </div>

    <% end %>
</div>

app/views/partials/_book_review_form.html.erb
<div class="general-review-form">
    <%= form_for(@book_review, url: url) do |f| %>
        <%= render "users/shared/error_messages", resource: @book_review %>
        
        <div class="field">
            <%= f.label :title, class: "" %>
            <%= f.text_field :title, class: "" %>
        </div>

        <div class="field">
            <%= f.label :author, class: "" %>
            <%= f.text_field :author, class: "" %>
        </div>

        <div class="field">
            <%= f.label "Attach", class: "" %>
            <%= f.file_field :avatar, class: "" %>
        </div>
        
        <div class="field">
            <%= f.label :rating, class: "" %>
            <%= f.number_field :rating, class: "",step: "any", min: 0, max: 5 %>  
        </div>

        <div class="field">
            <%= f.label :published, class: "" %>
            <%= f.date_field :published, class: "" %>
        </div>

        <div class="field">
            <%= f.label :genre, class: ""  %>
            <%= f.select :genre, options_for_select(['Fiction', 'Non-Fiction', 'Fantasy','Mystery', 'History', 'Science','Romance', 'Spirituality', 'Technology','Horror', 'Not Specified']), { prompt: " -- Select One -- "}, { class: "form-control", placeholder:" " } %>
            
        </div>

        <div class="field">
            <%= f.label :review, class: "" %>
            <%= f.text_area :review, class: "", rows: 15, cols: 95 %>
        </div>

        <div class="actions">
            <% if action == "new" %>
                <%= f.submit "Create", class: "", id: "" %>
            <% else %>
                <%= f.submit "Update", class: "", id: "" %>
            <% end %>
        </div>

    <% end %>
</div>

app/views/partials/_book_review_index.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <div class="sub-heading-header">
            <div class="tab-header">
                <h3> Book Reviews</h3>
            </div>
            <div class="add-new-container">
                <%= icon "plus" %>
                <span><%= link_to "Add Review", new_book_review_path, class: "add-new", data: { turbo: false} %></span>
            </div>
        </div>
        <div class="reviews-main-content">
            <div class="left-main-content book-review-content">
                <% @book_reviews.each do |review| %>
                    <%= link_to book_review_path(review), class: "book-full-review-link", data: { turbo: false} do %>    
                        <div class="book-card">
                            <div class="book-card-image"><%= image_tag review.avatar.url, class: "book-image" %></div>
                            <div class="book-container">
                                <h4>by <%= review.author %></h4>
                                <p> <%= render_stars(review.rating) %></p>
                            </div>
                        </div>
                    <% end %>
                <% end %>
                <%= paginate @book_reviews %>
            </div>
            <div class="right-main-content">
                <div class="tab-heading-description">
                    <% if action != "index" %>    
                        <h3> <%= action.camelize %> </h3>
                    <% else %>
                        <h3> About </h3>
                    <% end %>
                    <p> <%= genre_description(action) %> </p>
                </div>
                <div class="sidebar-content">
                    <div class="sidebar-sub-header">
                        <h2> Categories </h2>
                    </div>
                    <div class="books-navbar">   
                        <%= tabs_tag :namespace => :navigation do |tab| %>
                            <%= tab.index 'All Books', book_reviews_path, class: "book-links" %>
                            <%= tab.fiction 'Fiction', fiction_book_reviews_path, class: "book-links" %>
                            <%= tab.history 'History', history_book_reviews_path, class: "book-links" %>
                            <%= tab.non_fiction 'Non-Fiction', non_fiction_book_reviews_path, class: "book-links" %>
                            <%= tab.mystery 'Mystery', mystery_book_reviews_path, class: "book-links" %>
                            <%= tab.science 'Science', science_book_reviews_path, class: "book-links" %>
                            <%= tab.romance 'Romance', romance_book_reviews_path, class: "book-links" %>
                            <%= tab.spirituality 'Spirituality', spirituality_book_reviews_path, class: "book-links" %>
                            <%= tab.fantasy 'Fantasy', fantasy_book_reviews_path, class: "book-links" %>
                        <% end %>
                    </div
                </div>
            </div>
        </div>
    </main>
</body>

app/views/partials/_common_header.html.erb
<div class="dashboard-container">
    <header class="dashboard-heading">
        <div class="dashboard-header-content dashboard-date-field">
            <%= Date.today.strftime("%B %e, %Y") %>
        </div>
        <div class="dashboard-header-content dashboard-header">
            <%= link_to dashboard_index_path, class: "dashboard-header-link", data: { turbo: false} do%>
                <h1> The Newsroom </h1>
            <% end %>    
        </div>
        <div class="dashboard-header-content dashboard-header account-links">
            <div class="user-account">
                <%= icon "square-user-round" %>
                <span><%= link_to "Account", edit_user_registration_path, class: "user-account-link", data: { turbo: false} %></span>
            </div>
            <span><%= link_to "Logout", destroy_user_session_path, class: "logout-link", data: { turbo_method: :delete } %></span>
        </div>
    </header>
    <div class="dashboard-navbar">
        <%= tabs_tag(:builder => CustomTabsBuilder) do |tab| %>
            <%= tab.news 'News', "", class: "dashboard-links" %>
            <%= tab.articles 'Articles', articles_path, class: "dashboard-links" %>
            <%= tab.game_reviews 'Game Reviews', game_reviews_path, class: "dashboard-links" %>
            <%= tab.book_reviews 'Book Reviews', book_reviews_path, class: "dashboard-links" %>
        <% end %>
    </div>
</div>  

app/views/partials/_game_review_form.html.erb
<div class="general-review-form">
    <%= form_for(@game_review, url: url) do |f| %>
        <%= render "users/shared/error_messages", resource: @game_review %>
        
        
        <div class="field">
            <%= f.label :title, class: "" %>
            <%= f.text_field :title, class: "" %>
        </div>

        <div class="field">
            <%= f.label "Attach", class: "" %>
            <%= f.file_field :avatar, class: "" %>
        </div>
        
        <div class="field">
            <%= f.label :rating, class: "" %>
            <%= f.number_field :rating, class: "", min: 0, max: 100 %>  
        </div>

        <div class="field">
            <%= f.label :release, class: "" %>
            <%= f.date_field :release, class: "" %>
        </div>
        

        <div class="field">
            <%= f.label :short_description, class: "" %>
            <%= f.text_area :short_description, class: "", rows: 4, cols: 95 %>
        </div>

        <div class="field">
            <%= f.label :review, class: "" %>
            <%= f.text_area :review, class: "", rows: 15, cols: 95 %>
        </div>

        <div class="actions">
            <% if action == "new" %>
                <%= f.submit "Create", class: "", id: "" %>
            <% else %>
                <%= f.submit "Update", class: "", id: "" %>
            <% end %>
        </div>

    <% end %>
</div>