config/routes.rb
Rails.application.routes.draw do
  get "dashboard/index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  get "pages/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "pages#index"

  resources :game_reviews
  resources :book_reviews do 
    collection do 
      get :fiction
      get :history
      get :non_fiction
      get :mystery
      get :science
      get :romance
      get :spirituality
      get :fantasy
    end
  end
  resources :articles
end

app/controllers/game_reviews_controller.rb
class GameReviewsController < ApplicationController
    before_action :authenticate_user!
    set_tab :game_reviews

    def index
        @game_reviews = GameReview.order(release: :desc).page(params[:page])
        @recent_Reviews = GameReview.order(created_at: :desc).limit(5)
    end

    def new
        @game_review = GameReview.new
    end

    def show
        @game_review = GameReview.find(params[:id])
    end

    def edit
        @game_review = GameReview.find(params[:id])
    end

    def create
        @game_review = GameReview.new(game_review_params)
        if @game_review.save
            redirect_to game_reviews_path, notice: "Review saved successfully"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        @game_review = GameReview.find(params[:id])
        if @game_review.update(game_review_params)
            redirect_to game_review_path(@game_review), notice: "Review updated successfully"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private 

    def game_review_params
        params.require(:game_review).permit!
    end
end

app/helpers/game_reviews_helper.rb
module GameReviewsHelper
    def ratings_helper(rating)
        if  rating >= 90
            return "Masterpiece"
        elsif rating >= 80  && rating < 90
            return "Amazing"
        elsif rating >= 70  && rating < 80
            return "Great"
        elsif rating >= 60  && rating < 70
            return "Good"      
        else
            return "Average"
        end
    end
end

app/views/game_reviews/edit.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <div class="sub-heading-header">
            <div class="tab-header">
                <h3> Edit Game Review</h3>
            </div>
        </div>
        <div class="game-review-form">
            <%= form_for(@game_review, url: game_review_path(@game_review)) do |f| %>
                <%= render "users/shared/error_messages", resource: @game_review %>
                
                
                <div class="formGroup">
                    <%= f.label :title, class: "game-review-lables" %>
                    <%= f.text_field :title, class: "form-field-uniform" %>
                </div>

                <div class="formGroup">
                    <%= f.label "Attach", class: "game-review-lables" %>
                    <%= f.file_field :avatar, class: "image-field" %>
                </div>
                
                <div class="formGroup">
                    <%= f.label :rating, class: "game-review-lables" %>
                    <%= f.number_field :rating, class: "form-field-uniform", min: 0, max: 100 %>  
                </div>

                <div class="formGroup">
                    <%= f.label :release, class: "game-review-lables" %>
                    <%= f.date_field :release, class: "form-field-uniform" %>
                </div>
                

                <div class="formGroup">
                    <%= f.label :short_description, class: "game-review-lables" %>
                    <%= f.text_area :short_description, class: "form-field-uniform", rows: 3 %>
                </div>

                <div class="formGroup">
                    <%= f.label :review, class: "game-review-lables" %>
                    <%= f.text_area :review, class: "form-field-uniform", rows: 15 %>
                </div>

                <div class="form-actions">
                    <%= f.submit "Update", class: "game-review-submit" %>
                </div>

            <% end %>
        </div>
    </main>
</body>

app/views/game_reviews/index.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <div class="sub-heading-header">
            <div class="tab-header">
                <h3> Game Reviews</h3>
            </div>
            <div class="add-new-container">
                <%= icon "plus" %>
                <span><%= link_to "Add Review", new_game_review_path, class: "add-new", data: { turbo: false} %></span>
            </div>
        </div>
        <div class="reviews-main-content">
            <div class="left-main-content">
                <% @game_reviews.each do |review| %>
                <div class="game-review-card">
                    <div class="review-image-box">
                        <%= image_tag review.avatar.url, class: "game-image" %>
                    </div>
                    <div class="review-content">
                        <%= link_to game_review_path(review), class: "full-review-link", data: { turbo: false} do %>
                            <p class="review-title"><%= review.title %><p>
                        <% end %>
                        <p class="review-description"><%= review.short_description %></p>
                        <p class="review-release"><%= review.release.strftime("%B %e, %Y") %></p>
                        <p class="review-rating"><%= review.rating %></p>
                    </div>
                </div>
                <% end %>
                <%= paginate @game_reviews %>
            </div>
            <div class="right-main-content">
                <div class="tab-heading-description">
                    <h3> About </h3>
                    <p> Find your next captivating gaming moment. Reviews about a wide variety of games across multiple genre's. Each review is scored to a maximim of 100, based on several factors and it's overall quality. </p>
                </div>
                <div class="sidebar-content">
                    <div class="sidebar-sub-header">
                        <h2> Recent Reviews </h2>
                    </div>
                    <% @recent_Reviews.each do |recent_review| %>
                        <div class="sidebar-review-card">
                            <div class="sidebar-image-box">
                                <%= image_tag recent_review.avatar.url, class: "sidebar-image" %>
                            </div>
                            <div class="sidebar-review-content">
                                <%= link_to game_review_path(recent_review), class: "full-review-link", data: { turbo: false} do %>
                                    <p class="review-title"><%= recent_review.title %><p>
                                <% end %>
                                <p class="review-release"><%= recent_review.release.strftime("%B %e, %Y") %></p>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </main>
</body>

app/views/game_reviews/new.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <div class="sub-heading-header">
            <div class="tab-header">
                <h3> New Game Review</h3>
            </div>
        </div>
        <%= render "partials/game_review_form", url: game_reviews_path(@game_review), action: "new" %>
    </main>
</body>

app/views/game_reviews/show.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <div class="full-review-content">
        <div class="full-review-header">
            <div><%= link_to "Back", game_reviews_path, class: "full-review-back", data: { turbo: false} %></div>
            <div class=""><h2><%= @game_review.title %> - Review</h2></div>
            <div class=""><%= link_to "Edit", edit_game_review_path(@game_review), class: "full-review-edit", data: { turbo: false} %></div>
        </div>
        <div class="full-review-image">
            <%= image_tag @game_review.avatar.to_s, class:"game-image" %>
        </div>
        <div class="full-review-review">
            <p><%= simple_format(@game_review.review) %></p>
        </div>
        <div class="full-review-rating"> 
            <%= @game_review.rating %>
        </div>
        <div class="full-review-text-verdict">
            <%= ratings_helper(@game_review.rating) %>
        </div>
    </div>
</body>